### ISSUE TITLE
[Editor] "Clear unused data" command has wiped custom folder contents completely.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#119]
Title says all.
Before:
![unused_wipe1](https://cloud.githubusercontent.com/assets/7596025/14723142/367165a4-0818-11e6-8f46-c732155699ee.png)
After:
![unused_wipe2](https://cloud.githubusercontent.com/assets/7596025/14723148/3ccfe7b8-0818-11e6-9557-feb13ee1efac.png)
Affected level: https://yadi.sk/d/7dyHRM24rC2jn
Thanks for backup, it makes easier to restore from this bug.

**Comment by Wohlstand** [comment]
Totally forgot about usued data cleaner... I made that as a small experiment, and it based on SMBX-64 standard only, therefore new result is invalid. So, I'll continue work on it and it must be finished

P.S. I kept backup making because other reasons: some files are may be useful for another purposes, and I'll let users choice what do with those files - delete them or move away to another place

**Comment by Wohlstand** [comment]
Just now I reworked this feature, now it should work!
Please test the work...

**Comment by Alucard648** [comment]
Thanks foe fixing. Now works as intended, no more total wiping.

**Comment by Wohlstand** [comment]
The main reason for this mess was a relying on GIFs with no counting of PNGs. Also, I had to add counting of INI configs and looking for any possible mentions in local scripts and configs. So, I closing this as a completed.
