### ISSUE TITLE
[PGE MusPlay] Pause button does not work with Native MIDI device.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#158]
1. Open MIDI file in MusPlay.
2. Set MIDI device to Native MIDI.
   Pause button don`t stop MIDI playback at all. AdlMidi device works properly in this case.

**Comment by Wohlstand** [comment]
It's SDL Mixer side trouble which was presented before I forked it into SDL Mixer X. So, I think, i'll try to fix that with experiment against midiStreamPause function. Anyway, another strong reason why I used AdlMidi as deault device: when you will try fadeout with Native-MIDI (especially while Microsoft GS synthesizer is toggled as default MIDI output device, with custom synthesizer drivers everything is fine), [it will mute sound of entire computer](http://www.supermariobrosx.org/forums/viewtopic.php?p=117906#p117906) (not because wrong management, because silly WinAPI's midiOutSetVolume (which must change volume only of this stream, not for entire audio channel!) )

**Comment by Wohlstand** [comment]
Good news!
After recent reorganizing inside SDL Mixer X the Native Midi is finally affects pause action! The last thing is making the real-time MIDI playing to take very important advantage to escape the bug of MS GS that causes changing of master volume instead of music by itself

**Comment by Alucard648** [comment]
Thanks. Now native midi playback pauses as intanded.
