### ISSUE TITLE
Position Bookmarks don`t remember section number.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#171]
1. Bookmark a position in section 1.
2. Go to section 2.
3. Double-click on bookmark.

You get to bookmarked position, but it is shaded out as it`s outside current section (#2) which is not switched. Clicking on Section 1 lights it on as expected. This bug exists only for sections <= 21. For PGE exclusive sections (>21) position bookmarks work fine.

**Comment by Wohlstand** [comment]
Seems a small inaccuracy in nearest section detection (no need remember section id since it can be easily detected by position (in PGE Engine is almost same algorithm when player going between warp points), because left-top corner of viewport is not so good point and I need use relative center of viewport (which is different dependent on window size and zoom).

**Comment by Wohlstand** [comment]
Please check how it works.
New nearest section detection must work. I'll repeat, here is no need to remember absolute section ID, instead need to accurately detect section which has nearest position between it's center or one of it's corners

**Comment by Alucard648** [comment]
Works like magic!

**Comment by Wohlstand** [comment]
I also recently added another small fix: because if you will make small section and you will move it to place under/over another huge, detector may be confused and will detect smaller section even camera inside huge (because that smaller section is "nearest" than corners and center of same huge section)
