### ISSUE TITLE
Instant warps placed right behind section boundary fail to work

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#179]
Character cannot enter instant warp that is placed just beyond section boundary, like this one:
![instant_warp](https://cloud.githubusercontent.com/assets/7596025/20780712/420583a2-b78e-11e6-9666-274989d523b5.png)
Test level: https://yadi.sk/d/vRYGQmmzztPLK
In LunaLua, warps like this work fine.

**Comment by Wohlstand** [comment]
The thing is player blocked by section boundary. Seems I need allow player to go 1 extra pixel to let player touch this warp point

**Comment by Wohlstand** [comment]
Fixed!
![scr_2016_12_1_15_28_12_474](https://cloud.githubusercontent.com/assets/6751442/20794170/4e1f397a-b7e4-11e6-818a-322c4b43e086.gif)
I did by expanding horizontal section boundaries limit with 1 pixel instead extending width of warp point to disallow a going through warp point on the block top (in legacy engine it sometimes caused accidentall going through this warp which blocked by block, and which in some cases resulted a trap (because with that block, other are still be visible and no way access them))

**Comment by Alucard648** [comment]
For some reason, this fix don`t appear in latest dev build (December 1 2016, 15:48;03).

**Comment by Wohlstand** [comment]
Please compare hash code of commit (revision) at latest commit and in title bar of engine application. Maybe you still use old build

**Comment by Alucard648** [comment]
Online downloader still installs outdated build (3 days ago).

**Comment by Wohlstand** [comment]
Weird, maybe avast plays evil joke with you, or you installed into another folder, but old version is kept in same folder

**Comment by Wohlstand** [comment]
P.S. This fix I sent globally to everywhere, even into stable

**Comment by Alucard648** [comment]
Thanks for help. Build is now up to date. 
On topic: fix confirmed. Thaks.
