### ISSUE TITLE
[Engine] 3 engine issues

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/PGE-Project#209]
- [x]  If NPC is placed on top of block that is on upwards moving layer, he will spawn inside block on level startup.

- [x] If NPC encounters slope top while walking on upwards moving layer he will sometimes turn around as if it bumps into solid wall.

- [x] Hitting jimp button in the exactly same frame the playable caracter steps on slope top after moving on upward slope results in control response failure.
![slope_top2](https://cloud.githubusercontent.com/assets/7596025/25153304/c401f520-2494-11e7-8f8c-d8c0b9b539c1.png)
Blue arrow - movement prior to jumping.
Yellow arrow - expected result after hitting jump button
Red arrow - actual movement - control failure

All 3 issues can be reproduced in this test level: https://yadi.sk/d/XXYw4GmN3H7cJ7

**Comment by Wohlstand** [comment]
1) That explainable: when layer starts it's movement, NPC still asleep, but it gets be activated on next moment: when camera will fetch for a visible objects and will wake up all vizible NPCs, and then NPCs getting woke up in moment thee are lower than floor. That seems a necessary to ask for visible NPCs a bit differently, or let NPCs automatically aligned on the layer more correctly
2) That also explainable, because of missing calculations are done without counting of movement of blocks by theme selves
3) The jump must happen, but in result when physical engine had aligned player to floor while rising slope, will check out for reason

**Comment by Wohlstand** [comment]
Please test the 3'rd, some time ago I have fixed slope-related bug that caused a player to stumble over a corner.

**Comment by Alucard648** [comment]
As of current development build, all 3 items in this ticket appears to be fixed.

**Comment by Wohlstand** [comment]
Great! :fox_face: 
Didn't though that first was fixed, however, it's just good that this bug also has gone! :grin: 

So, the problem was solved!

**Comment by Alucard648** [comment]
Oops! Did a more extensive test and discovered that inactive NPC`s that assigned to a moving layer don`t move with layer. Ticket neds to be reopened with item 1 still unresolved.

**Comment by Wohlstand** [comment]
When inactive NPCs aren't moving together with a layer, it's a different bug, and I know the solution for it - stick on a layer until activate, then, unstick if NPC is dynamical and should freely move in a free space.
