### ISSUE TITLE
[Editor] Change background color in "About" box

### ISSUE THREAD

**Issue by NathanBnm** [WohlSoft/PGE-Project#307]
Same type as #305. Here the text is in black on a darkblue background. This makes the text difficult to read too.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/67427906-5ab68780-f5dd-11e9-8e12-3ef83ee23c06.png)

**Comment by Wohlstand** [comment]
This dialog box was tuned on Windows in an era of Windows 7 and it was intended to use Aero glass style here. (On other platforms and on older Windows versions this effect is the absence).

![Снимок экрана_2019-10-23_22-45-52](https://user-images.githubusercontent.com/6751442/67428498-e7197800-f5e6-11e9-8810-7f7359ce26a0.png)

Since Windows 8 this beautiful effect is lost, and on referring your example, it becomes not like intended. So, I have an idea - I'll avoid this effect on any Windows other than 7 on this dialog. Windows 8.1 and higher will show the same view as on Windows XP without turning the stuff into the glass. Another way is recognizing the color and automatically tune the text color between lighter/darker hue to make it's showing correctly here. However, I have no idea how to recognize this here, possibly, hack through WinAPI :thinking:

**Comment by NathanBnm** [comment]
Oh well, I understand! Just keep in mind that Windows XP is not supported anymore, and Windows 7 soon as well. So no need to worry so much about this I think.

**Comment by Wohlstand** [comment]
All 32-bit builds I producing are keeping Windows XP compatibility (Qt 5.6 for deployment) because some people are still using it (because of their hardware sucks and won't allow work even at least Windows 7, and they aren't ready to move to Linux). All 64-bit Windows builds are trying to use the latest Qt (however, in some moments I would don't update it after few next Qt releases, I using my own Qt builds for this).

The mentioning of Windows XP here was because of current logic in this dialog to skin the dialog like you see or don't that. I meant, as an option, apply the same logic as for Windows XP on Windows 8.1 and 10, and keep the glass effect on Windows 7.

**Comment by Wohlstand** [comment]
It's how dialog is showing on Windows XP:
![Снимок экрана_2019-10-23_22-58-46](https://user-images.githubusercontent.com/6751442/67429366-af133480-f5e8-11e9-994d-12afd7c3fa7a.png)

On Linux Mint:
![Снимок экрана от 2019-10-23 23-00-14](https://user-images.githubusercontent.com/6751442/67429471-e7b30e00-f5e8-11e9-8734-4ea2a16a51a7.png)

As you can see, there are no attempts to "making a glass effect". As I said, I have two options:
* Do the same view on Windows 8.1/10+ as on Windows XP and other non-Windows platforms.
* Keep this effect, but, implement a text color tuning to avoid the bad view on darker colors.

**Comment by NathanBnm** [comment]
I am for the first solution because in my opinion the aero effect doesn't fit well with Windows 8 / 10.

**Comment by Wohlstand** [comment]
Ok, made it just now :fox_face: :+1: 
It should look like on Windows XP now.
