### ISSUE TITLE
[Editor] Remove MainWinConnect

### ISSUE THREAD

**Issue by KevinW1998** [WohlSoft/PGE-Project#61]
This is essential for the editor for better future development, especially when it comes to GUI alternatives. 

My suggestions for replacements are:
- Using signals & slots for callbacks or
- Using std::function callbacks
- Using a callback class

MainWinConnect just doesn't fit good as good programming, as the scene depends on the gui, **which shouldn't be**!

**Comment by Wohlstand** [comment]
Since editor reorganizing will result new code base, this will be completely avoided.

For the old base this is  still be very important global unit and is very important to keep it. Partially some set of existing modules has been avoided usage of this unit, and new modules are avoiding usage of it and keeps the main window pointer inside it's class with receiving source pointer in their constructors.

**Comment by Alucard648** [comment]
How long it will take to finish reorganizing?

**Comment by Wohlstand** [comment]
At first, I must finish ItemSceme module which is very important, and then begin building the new editor base. Anyway, for now, I focused on the engine to implement it faster, and the editor still useful even for now, and I just keeping support for it on any bug reports. Engine counterpart is wanted by many people, and even SMBX 2.0 is planned to use it on it's finishing. Legacy Engine is uncontrollable even we are possible to hack it from many sides, and weird bugs by any unexpected moment can appear, by the mean way, and some of them are unfixable because of weird WinAPI side things.

New editor's scheme we are designing here:
https://github.com/WohlSoft/PGE-Project/tree/master/Documents/Editor
(to view it, you need the yED program: http://www.yworks.com/products/yed)
It's how we are a plan to build the new base of the editor where we are will move all existing features into it.

**Comment by Wohlstand** [comment]
Blocked. It's a part of huge editor reorganize when it's base will be completely rewritten from scratch with a new architecture.

**Comment by Wohlstand** [comment]
In closer future, I do plan the major rework of the Editor's codebase, with the current codebase this task won't be solved at all as there are a lot of places that still use the global pointer to the main window for their work. I better rewrite the Editor codebase from the scratch rather I'll support this shit filled with bugs and mistakes of youth.
